### PR TITLE
insert wuguotai into rebel.txt

### PR DESCRIPTION
**Pull request by dragon100a**

### CODE REVIEW

**Comment by dragon100a** [comment]
Wuguotai can be the core role of rebels during caopi's stage. Fangzhu "gives" more cards to the rebel. But buyi "changes" one non-standard card into a "peach" which saves the rebel.

**Comment by Fsu0413** [comment]
@zyun7799 你看看能不能合

**Comment by zyun7799** [comment]
要不要这么麻烦嘛。。。三个单词的事情。。。还搞个pull request，去bug反馈贴说一声我自然会看到的

**Comment by dragon100a** [comment]
1.I have no idea that what you mean.
I had mentioned this case at the following page in tieba.
http://tieba.baidu.com/p/3720357146
8#, on April 25.
On May 1, I mentioned this case here.
https://github.com/Mogara/QSanguosha-v2/pull/51

I mentioned this case at both tieba and here.

Till May 9, I still have no reply. I am not sure where your eyes goes.
Therefore, I submit this request to solve this problem.

2.Pull request is a formal and fast way for one without privilege to contribute code.
It just took 4 days to solve this problem.(5.9~13) by pull request.
In tieba, this problem still existed, then 2 weeks had passed.

**Pull request merged**
